
# dockerfile manyline:

FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl 

RUN mkdir -p /opt/jboss/wildfly
 
RUN cd /tmp 

RUN curl -O https://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz 

RUN tar xf wildfly-10.1.0.Final.tar.gz  

RUN mv wildfly-10.1.0.Final /opt/jboss/wildfly 

RUN rm wildfly-10.1.0.Final.tar.gz